---
prezto_repo: https://github.com/sorin-ionescu/prezto.git
prezto_dest: "{{ ansible_env.HOME }}/.zprezto"

prezto_runcoms:
  - zlogin
  - zlogout
  # zpreztorc is managed via stow (zsh/.zpreztorc)
  - zprofile
  - zshenv
  - zshrc
