---
dnf_packages:
  - ansible
  - awscli2
  - ffmpeg-free
  - gh
  - gnupg2
  - jq
  - nmap-ncat
  - nodejs
  - npm
  - p7zip
  - ripgrep
  - stow
  - tmux
  - zsh
  - yt-dlp
  - mariadb-server
  - golang
  # New packages
  - pipx
  - helm
  - git-filter-repo
  - unar

dnf_desktop_packages:
  - imhex
  - geary
  - celluloid
  - weechat

flatpak_apps:
  - io.github.zen_browser.zen
  - it.mijorus.smile
  - rest.insomnia.Insomnia
  - com.usebottles.bottles
  - org.kde.audiotube
  - tv.plex.PlexDesktop

npm_packages:
  - yarn
  - "@withgraphite/graphite-cli"

go_packages:
  - github.com/segmentio/golines@latest
